server:
  port: 9248

# Discovery Service Settings
# --------------------------
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
  server:
    enableSelfPreservation: true

# Log settings
# ------------
logging:
  level:
    com.netflix: ERROR
    org.springframework: ERROR
    com.harik.inno: INFO

# Database properties
spring:
  application:
    name: authentication-service
  datasource:
    driverClassName: ${DB_DRIVER_CLASS:org.postgresql.Driver}
    platform: postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Test123$}
    url: jdbc:postgresql://${DB_HOST:192.168.204.241}:${DB_SERVER_PORT:5432}/${DB_NAME:ecomdb}?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    # set generate-ddl as false before pushing to production
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: dbauth
        # Set the ddl-auto to none before pushing to production.
        #ddl-auto: none
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
# API Documentation settings
com.harik.configuration:
  security:
    endpoints:
      unsecured:
        - "/v3/api-docs/**"
        - "/swagger-ui.html"
        - "/swagger-ui/**"
        - "/actuator/**"
    api:
      documentation:
        title: TrailApp
        description: trailapp
    auth:
      token:
        secret: isymphony
        expiration-interval-in-hours: 168

# Information that gets displayed in the spring admin UI
# ------------------------------------------------------
info:
  app:
    name: ${spring.application.name}
    description: Authentication Service for application.